const builtInExerciseLibrary = [
  // Chest
  { id: "barbell-bench-press", name: "Barbell Bench Press", muscle: "Chest", equipment: "Barbell", pattern: "press", style: "compound", logging: "weight", note: "Plant your feet and lower the bar with control." },
  { id: "cable-fly", name: "Cable Fly", muscle: "Chest", equipment: "Cables", pattern: "fly", style: "accessory", logging: "weight", note: "Keep a soft elbow bend and bring your hands together." },
  { id: "chest-dip", name: "Chest Dip", muscle: "Chest", equipment: "Bodyweight", pattern: "press", style: "compound", logging: "reps", note: "Lean slightly forward and keep your shoulders down." },
  { id: "decline-barbell-bench-press", name: "Decline Barbell Bench Press", muscle: "Chest", equipment: "Barbell", pattern: "press", style: "compound", logging: "weight", note: "Secure your legs and touch the bar low on your chest." },
  { id: "dumbbell-bench-press", name: "Dumbbell Bench Press", muscle: "Chest", equipment: "Dumbbells", pattern: "press", style: "compound", logging: "weight", note: "Lower evenly and keep your wrists stacked." },
  { id: "incline-barbell-bench-press", name: "Incline Barbell Bench Press", muscle: "Chest", equipment: "Barbell", pattern: "press", style: "compound", logging: "weight", note: "Use a moderate incline and keep your shoulder blades set." },
  { id: "incline-dumbbell-bench-press", name: "Incline Dumbbell Bench Press", muscle: "Chest", equipment: "Dumbbells", pattern: "press", style: "compound", logging: "weight", note: "Press up and slightly inward without clanking the weights." },
  { id: "low-to-high-cable-fly", name: "Low-to-High Cable Fly", muscle: "Chest", equipment: "Cables", pattern: "fly", style: "accessory", logging: "weight", note: "Sweep the handles upward toward your upper chest." },
  { id: "machine-chest-press", name: "Machine Chest Press", muscle: "Chest", equipment: "Machines", pattern: "press", style: "compound", logging: "weight", note: "Set the seat so the handles begin near mid-chest." },
  { id: "pec-deck", name: "Pec Deck (Chest Fly Machine)", muscle: "Chest", equipment: "Machines", pattern: "fly", style: "accessory", logging: "weight", note: "Keep your back against the pad and squeeze smoothly." },
  { id: "smith-machine-bench-press", name: "Smith Machine Bench Press", muscle: "Chest", equipment: "Machines", pattern: "press", style: "compound", logging: "weight", note: "Position the bench so the bar tracks over mid-chest." },
  { id: "standard-push-up", name: "Standard Push-Up", muscle: "Chest", equipment: "Bodyweight", pattern: "press", style: "compound", logging: "reps", note: "Keep your body straight and lower your chest between your hands." },
  { id: "wide-push-up", name: "Wide Push-Up", muscle: "Chest", equipment: "Bodyweight", pattern: "press", style: "accessory", logging: "reps", note: "Place hands wider than shoulders without flaring excessively." },

  // Back
  { id: "barbell-row", name: "Barbell Row", muscle: "Back", equipment: "Barbell", pattern: "row", style: "compound", logging: "weight", note: "Brace your torso and pull the bar toward your lower ribs." },
  { id: "cable-straight-arm-pulldown", name: "Cable Straight-Arm Pulldown", muscle: "Back", equipment: "Cables", pattern: "vertical pull", style: "accessory", logging: "weight", note: "Keep your arms nearly straight and pull toward your thighs." },
  { id: "chin-up", name: "Chin-Up", muscle: "Back", equipment: "Bodyweight", pattern: "vertical pull", style: "compound", logging: "reps", note: "Use an underhand grip and pull your chest toward the bar." },
  { id: "close-grip-lat-pulldown", name: "Close-Grip Lat Pulldown", muscle: "Back", equipment: "Machines", pattern: "vertical pull", style: "compound", logging: "weight", note: "Keep your chest tall and draw your elbows down." },
  { id: "conventional-deadlift", name: "Conventional Deadlift", muscle: "Back", equipment: "Barbell", pattern: "hinge", style: "compound", logging: "weight", note: "Brace before lifting and keep the bar close to your legs." },
  { id: "inverted-row", name: "Inverted Row", muscle: "Back", equipment: "Bodyweight", pattern: "row", style: "compound", logging: "reps", note: "Keep your body rigid and pull your chest to the bar." },
  { id: "kettlebell-row", name: "Kettlebell Row", muscle: "Back", equipment: "Kettlebells", pattern: "row", style: "compound", logging: "weight", note: "Keep your hips square and pull toward your back pocket." },
  { id: "lat-pulldown", name: "Lat Pulldown", muscle: "Back", equipment: "Machines", pattern: "vertical pull", style: "compound", logging: "weight", note: "Pull to your upper chest without leaning far backward." },
  { id: "machine-assisted-chin-up", name: "Machine-Assisted Chin-Up", muscle: "Back", equipment: "Machines", pattern: "vertical pull", style: "compound", logging: "assistance", note: "Use an underhand grip and let the machine assist smoothly." },
  { id: "machine-assisted-pull-up", name: "Machine-Assisted Pull-Up", muscle: "Back", equipment: "Machines", pattern: "vertical pull", style: "compound", logging: "assistance", note: "Stay tall and avoid bouncing on the assistance platform." },
  { id: "machine-row", name: "Machine Row", muscle: "Back", equipment: "Machines", pattern: "row", style: "compound", logging: "weight", note: "Keep your chest supported and finish with elbows behind you." },
  { id: "one-arm-dumbbell-row", name: "One-Arm Dumbbell Row", muscle: "Back", equipment: "Dumbbells", pattern: "row", style: "compound", logging: "weight", note: "Keep your back flat and pause at the top." },
  { id: "pull-up", name: "Pull-Up", muscle: "Back", equipment: "Bodyweight", pattern: "vertical pull", style: "compound", logging: "reps", note: "Start from a controlled hang and pull without swinging." },
  { id: "seated-cable-row", name: "Seated Cable Row", muscle: "Back", equipment: "Cables", pattern: "row", style: "compound", logging: "weight", note: "Stay tall and pull the handle toward your waist." },
  { id: "single-arm-cable-row", name: "Single-Arm Cable Row", muscle: "Back", equipment: "Cables", pattern: "row", style: "compound", logging: "weight", note: "Resist torso rotation as you pull." },

  // Legs
  { id: "barbell-back-squat", name: "Barbell Back Squat", muscle: "Legs", equipment: "Barbell", pattern: "squat", style: "compound", logging: "weight", note: "Brace first and keep your knees tracking over your toes." },
  { id: "barbell-front-squat", name: "Barbell Front Squat", muscle: "Legs", equipment: "Barbell", pattern: "squat", style: "compound", logging: "weight", note: "Keep your elbows high and torso upright." },
  { id: "bulgarian-split-squat", name: "Bulgarian Split Squat", muscle: "Legs", equipment: "Dumbbells", pattern: "lunge", style: "compound", logging: "weight", note: "Use a stable rear-foot support and lower straight down." },
  { id: "dumbbell-romanian-deadlift", name: "Dumbbell Romanian Deadlift", muscle: "Legs", equipment: "Dumbbells", pattern: "hinge", style: "compound", logging: "weight", note: "Push your hips back and keep the weights close." },
  { id: "dumbbell-squat", name: "Dumbbell Squat", muscle: "Legs", equipment: "Dumbbells", pattern: "squat", style: "compound", logging: "weight", note: "Keep the dumbbells stable and use a controlled depth." },
  { id: "forward-lunge", name: "Forward Lunge", muscle: "Legs", equipment: "Dumbbells", pattern: "lunge", style: "compound", logging: "weight", note: "Step far enough that your front heel stays grounded." },
  { id: "glute-bridge", name: "Glute Bridge", muscle: "Legs", equipment: "Bodyweight", pattern: "hinge", style: "accessory", logging: "reps", note: "Drive through your heels and finish by squeezing your glutes." },
  { id: "goblet-squat", name: "Goblet Squat", muscle: "Legs", equipment: "Dumbbells", pattern: "squat", style: "compound", logging: "weight", note: "Hold the weight close and keep your chest tall." },
  { id: "hack-squat", name: "Hack Squat", muscle: "Legs", equipment: "Machines", pattern: "squat", style: "compound", logging: "weight", note: "Keep your back on the pad and control the sled depth." },
  { id: "hip-thrust", name: "Hip Thrust", muscle: "Legs", equipment: "Barbell", pattern: "hinge", style: "compound", logging: "weight", note: "Keep your chin tucked and finish with level hips." },
  { id: "kettlebell-deadlift", name: "Kettlebell Deadlift", muscle: "Legs", equipment: "Kettlebells", pattern: "hinge", style: "compound", logging: "weight", note: "Hinge at the hips and stand tall without leaning back." },
  { id: "leg-extension", name: "Leg Extension", muscle: "Legs", equipment: "Machines", pattern: "knee extension", style: "accessory", logging: "weight", note: "Align your knees with the machine pivot and lift smoothly." },
  { id: "leg-press", name: "Leg Press", muscle: "Legs", equipment: "Machines", pattern: "squat", style: "compound", logging: "weight", note: "Keep your hips down and knees aligned with your toes." },
  { id: "lying-leg-curl", name: "Lying Leg Curl", muscle: "Legs", equipment: "Machines", pattern: "knee flexion", style: "accessory", logging: "weight", note: "Keep your hips against the pad as you curl." },
  { id: "reverse-lunge", name: "Reverse Lunge", muscle: "Legs", equipment: "Dumbbells", pattern: "lunge", style: "compound", logging: "weight", note: "Step back softly and drive through the front foot." },
  { id: "romanian-deadlift", name: "Romanian Deadlift", muscle: "Legs", equipment: "Barbell", pattern: "hinge", style: "compound", logging: "weight", note: "Keep a soft knee bend and hinge until your hamstrings load." },
  { id: "seated-calf-raise", name: "Seated Calf Raise", muscle: "Legs", equipment: "Machines", pattern: "calf raise", style: "accessory", logging: "weight", note: "Use a full stretch and pause at the top." },
  { id: "seated-leg-curl", name: "Seated Leg Curl", muscle: "Legs", equipment: "Machines", pattern: "knee flexion", style: "accessory", logging: "weight", note: "Keep your thighs secured and curl through a full range." },
  { id: "smith-machine-squat", name: "Smith Machine Squat", muscle: "Legs", equipment: "Machines", pattern: "squat", style: "compound", logging: "weight", note: "Set your feet so the fixed bar path feels natural." },
  { id: "split-squat", name: "Split Squat", muscle: "Legs", equipment: "Dumbbells", pattern: "lunge", style: "compound", logging: "weight", note: "Keep a stable stance and lower your rear knee vertically." },
  { id: "standing-calf-raise", name: "Standing Calf Raise", muscle: "Legs", equipment: "Machines", pattern: "calf raise", style: "accessory", logging: "weight", note: "Keep your knees soft and move through the ankle." },
  { id: "step-up", name: "Step-Up", muscle: "Legs", equipment: "Dumbbells", pattern: "lunge", style: "compound", logging: "weight", note: "Drive through the working foot without pushing off the floor." },
  { id: "walking-lunge", name: "Walking Lunge", muscle: "Legs", equipment: "Dumbbells", pattern: "lunge", style: "compound", logging: "weight", note: "Take controlled steps and keep your torso tall." },

  // Shoulders
  { id: "arnold-press", name: "Arnold Press", muscle: "Shoulders", equipment: "Dumbbells", pattern: "press", style: "compound", logging: "weight", note: "Rotate smoothly as you press without arching your back." },
  { id: "barbell-overhead-press", name: "Barbell Overhead Press", muscle: "Shoulders", equipment: "Barbell", pattern: "press", style: "compound", logging: "weight", note: "Brace your ribs down and finish with the bar overhead." },
  { id: "cable-face-pull", name: "Cable Face Pull", muscle: "Shoulders", equipment: "Cables", pattern: "rear delt", style: "accessory", logging: "weight", note: "Pull toward your face with elbows high and wide." },
  { id: "cable-lateral-raise", name: "Cable Lateral Raise", muscle: "Shoulders", equipment: "Cables", pattern: "lateral raise", style: "accessory", logging: "weight", note: "Lead with your elbow and stop around shoulder height." },
  { id: "cable-rear-delt-fly", name: "Cable Rear Delt Fly", muscle: "Shoulders", equipment: "Cables", pattern: "rear delt", style: "accessory", logging: "weight", note: "Pull your arms wide without shrugging." },
  { id: "dumbbell-front-raise", name: "Dumbbell Front Raise", muscle: "Shoulders", equipment: "Dumbbells", pattern: "front raise", style: "accessory", logging: "weight", note: "Lift under control and avoid leaning backward." },
  { id: "dumbbell-lateral-raise", name: "Dumbbell Lateral Raise", muscle: "Shoulders", equipment: "Dumbbells", pattern: "lateral raise", style: "accessory", logging: "weight", note: "Use soft elbows and raise without swinging." },
  { id: "dumbbell-shoulder-press", name: "Dumbbell Shoulder Press", muscle: "Shoulders", equipment: "Dumbbells", pattern: "press", style: "compound", logging: "weight", note: "Keep your ribs down and press evenly overhead." },
  { id: "leaning-cable-lateral-raise", name: "Leaning Cable Lateral Raise", muscle: "Shoulders", equipment: "Cables", pattern: "lateral raise", style: "accessory", logging: "weight", note: "Lean away slightly and keep steady cable tension." },
  { id: "machine-lateral-raise", name: "Machine Lateral Raise", muscle: "Shoulders", equipment: "Machines", pattern: "lateral raise", style: "accessory", logging: "weight", note: "Set the pads above your elbows and avoid shrugging." },
  { id: "machine-shoulder-press", name: "Machine Shoulder Press", muscle: "Shoulders", equipment: "Machines", pattern: "press", style: "compound", logging: "weight", note: "Adjust the seat so the handles start near shoulder height." },
  { id: "pike-push-up", name: "Pike Push-Up", muscle: "Shoulders", equipment: "Bodyweight", pattern: "press", style: "compound", logging: "reps", note: "Keep your hips high and lower your head between your hands." },
  { id: "rear-delt-machine", name: "Rear Delt Machine", muscle: "Shoulders", equipment: "Machines", pattern: "rear delt", style: "accessory", logging: "weight", note: "Keep your chest against the pad and pull wide." },
  { id: "reverse-dumbbell-fly", name: "Reverse Dumbbell Fly", muscle: "Shoulders", equipment: "Dumbbells", pattern: "rear delt", style: "accessory", logging: "weight", note: "Hinge forward and move from the shoulders, not momentum." },
  { id: "single-arm-cable-shoulder-press", name: "Single-Arm Cable Shoulder Press", muscle: "Shoulders", equipment: "Cables", pattern: "press", style: "compound", logging: "weight", note: "Brace your torso and press without rotating." },

  // Arms
  { id: "alternating-dumbbell-curl", name: "Alternating Dumbbell Curl", muscle: "Arms", equipment: "Dumbbells", pattern: "curl", style: "accessory", logging: "weight", note: "Keep your elbows still and alternate controlled reps." },
  { id: "barbell-curl", name: "Barbell Curl", muscle: "Arms", equipment: "Barbell", pattern: "curl", style: "accessory", logging: "weight", note: "Keep your torso quiet and elbows close." },
  { id: "bench-dip", name: "Bench Dip", muscle: "Arms", equipment: "Bodyweight", pattern: "extension", style: "accessory", logging: "reps", note: "Keep your shoulders down and stay close to the bench." },
  { id: "cable-curl", name: "Cable Curl", muscle: "Arms", equipment: "Cables", pattern: "curl", style: "accessory", logging: "weight", note: "Keep tension throughout and avoid moving your elbows." },
  { id: "cable-overhead-triceps-extension", name: "Cable Overhead Triceps Extension", muscle: "Arms", equipment: "Cables", pattern: "extension", style: "accessory", logging: "weight", note: "Keep elbows pointed forward as you extend." },
  { id: "cable-triceps-pressdown", name: "Cable Triceps Pressdown", muscle: "Arms", equipment: "Cables", pattern: "extension", style: "accessory", logging: "weight", note: "Pin your elbows to your sides and straighten fully." },
  { id: "close-grip-bench-press", name: "Close-Grip Bench Press", muscle: "Arms", equipment: "Barbell", pattern: "press", style: "compound", logging: "weight", note: "Use a shoulder-width grip and keep elbows controlled." },
  { id: "close-grip-push-up", name: "Close-Grip Push-Up", muscle: "Arms", equipment: "Bodyweight", pattern: "extension", style: "accessory", logging: "reps", note: "Keep hands near shoulder width and elbows close." },
  { id: "concentration-curl", name: "Concentration Curl", muscle: "Arms", equipment: "Dumbbells", pattern: "curl", style: "accessory", logging: "weight", note: "Brace your elbow against your thigh and curl slowly." },
  { id: "diamond-push-up", name: "Diamond Push-Up", muscle: "Arms", equipment: "Bodyweight", pattern: "extension", style: "accessory", logging: "reps", note: "Keep your hands close and stop if wrists feel strained." },
  { id: "dumbbell-curl", name: "Dumbbell Curl", muscle: "Arms", equipment: "Dumbbells", pattern: "curl", style: "accessory", logging: "weight", note: "Keep your elbows beside your torso and avoid swinging." },
  { id: "dumbbell-overhead-triceps-extension", name: "Dumbbell Overhead Triceps Extension", muscle: "Arms", equipment: "Dumbbells", pattern: "extension", style: "accessory", logging: "weight", note: "Keep elbows pointed up and lower behind your head." },
  { id: "ez-bar-curl", name: "EZ-Bar Curl", muscle: "Arms", equipment: "Barbell", pattern: "curl", style: "accessory", logging: "weight", note: "Use the angled grip that feels natural on your wrists." },
  { id: "hammer-curl", name: "Hammer Curl", muscle: "Arms", equipment: "Dumbbells", pattern: "curl", style: "accessory", logging: "weight", note: "Keep palms facing inward and elbows still." },
  { id: "incline-dumbbell-curl", name: "Incline Dumbbell Curl", muscle: "Arms", equipment: "Dumbbells", pattern: "curl", style: "accessory", logging: "weight", note: "Let your arms hang and avoid lifting your shoulders." },
  { id: "machine-curl", name: "Machine Curl", muscle: "Arms", equipment: "Machines", pattern: "curl", style: "accessory", logging: "weight", note: "Align your elbows with the machine pivot." },
  { id: "preacher-curl", name: "Preacher Curl", muscle: "Arms", equipment: "Barbell", pattern: "curl", style: "accessory", logging: "weight", note: "Keep your upper arms on the pad and avoid locking out hard." },
  { id: "rope-triceps-pressdown", name: "Rope Triceps Pressdown", muscle: "Arms", equipment: "Cables", pattern: "extension", style: "accessory", logging: "weight", note: "Separate the rope at the bottom without moving your elbows." },
  { id: "skull-crusher", name: "Skull Crusher", muscle: "Arms", equipment: "Barbell", pattern: "extension", style: "accessory", logging: "weight", note: "Keep upper arms steady and lower the bar under control." },

  // Core
  { id: "ab-wheel-rollout", name: "Ab-Wheel Rollout", muscle: "Core", equipment: "Bodyweight", pattern: "anti-extension", style: "accessory", logging: "reps", note: "Brace hard and roll only as far as you can control." },
  { id: "bear-plank", name: "Bear Plank", muscle: "Core", equipment: "Bodyweight", pattern: "anti-extension", style: "accessory", logging: "duration", note: "Hover your knees just off the floor and keep your back flat." },
  { id: "bicycle-crunch", name: "Bicycle Crunch", muscle: "Core", equipment: "Bodyweight", pattern: "rotation", style: "accessory", logging: "reps", note: "Rotate through your ribs rather than pulling your neck." },
  { id: "bird-dog", name: "Bird Dog", muscle: "Core", equipment: "Bodyweight", pattern: "anti-rotation", style: "accessory", logging: "reps", note: "Reach opposite arm and leg while keeping hips level." },
  { id: "cable-chop", name: "Cable Chop", muscle: "Core", equipment: "Cables", pattern: "rotation", style: "accessory", logging: "weight", note: "Move diagonally with control and keep your hips stable." },
  { id: "cable-crunch", name: "Cable Crunch", muscle: "Core", equipment: "Cables", pattern: "flexion", style: "accessory", logging: "weight", note: "Curl your ribs toward your hips without pulling with your arms." },
  { id: "dead-bug", name: "Dead Bug", muscle: "Core", equipment: "Bodyweight", pattern: "anti-extension", style: "accessory", logging: "reps", note: "Lower opposite arm and leg while keeping your back down." },
  { id: "hanging-knee-raise", name: "Hanging Knee Raise", muscle: "Core", equipment: "Bodyweight", pattern: "flexion", style: "accessory", logging: "reps", note: "Lift your knees without swinging." },
  { id: "hanging-leg-raise", name: "Hanging Leg Raise", muscle: "Core", equipment: "Bodyweight", pattern: "flexion", style: "accessory", logging: "reps", note: "Keep your legs controlled and avoid using momentum." },
  { id: "hollow-body-hold", name: "Hollow-Body Hold", muscle: "Core", equipment: "Bodyweight", pattern: "anti-extension", style: "accessory", logging: "duration", note: "Press your lower back down and keep the shape you can hold." },
  { id: "mountain-climber", name: "Mountain Climber", muscle: "Core", equipment: "Bodyweight", pattern: "dynamic", style: "accessory", logging: "reps", note: "Keep shoulders over hands and drive knees without bouncing." },
  { id: "plank", name: "Plank", muscle: "Core", equipment: "Bodyweight", pattern: "anti-extension", style: "accessory", logging: "duration", note: "Squeeze glutes, brace your core, and breathe steadily." },
  { id: "reverse-crunch", name: "Reverse Crunch", muscle: "Core", equipment: "Bodyweight", pattern: "flexion", style: "accessory", logging: "reps", note: "Curl your pelvis upward rather than swinging your legs." },
  { id: "side-plank", name: "Side Plank", muscle: "Core", equipment: "Bodyweight", pattern: "anti-lateral flexion", style: "accessory", logging: "duration", note: "Stack your body and keep your hips lifted." },
  { id: "weighted-dead-bug", name: "Weighted Dead Bug", muscle: "Core", equipment: "Dumbbells", pattern: "anti-extension", style: "accessory", logging: "weight", note: "Keep your lower back down as opposite limbs extend." }
];
